services:
  app:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.prod
    container_name: com-dajour-prod
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 80
    ports:
      - "80:80"
